### ISSUE TITLE
Question about the tutorial

### ISSUE THREAD

**Issue by Nesh108** [Germanunkol/OgreOculusSample#2]
Hello @Germanunkol,

This is not really an issue but I couldn't find a better way to contact you, so here I am.

I want to start saying that this tutorial is amazing. I have been searching for ages to find a decent and small tutorial for OculusRift and Ogre, this worked flawlessly.

I would like a suggestion and to know whether you did something like this already:
I would like change a bit the project and instead of doing VR (using the scene and the room), I would like to stream the content of the webcam to the left/right eye. Do you know how to do that?

I tried writing directly onto the textures using:

```
mLeftEyeRenderTexture->getBuffer()->lock(Ogre::HardwareBuffer::HBL_DISCARD);
mLeftEyeRenderTexture->getBuffer()->blitFromMemory(mPixelBox);
mLeftEyeRenderTexture->getBuffer()->unlock();
```

It did not work and those seem to be the only objects allowing me to blitFromMemory.

Any hint?

Thanks and sorry to bother you for this non-issue.

Keep up the good work!

/N.

**Comment by Germanunkol** [comment]
Hey,
Thanks a lot for the kind words! Really glad that this is helping you.

I've never really used dynamic content for textures. However, this seems to be something that many people would be doing a lot of times - rendering camera content into RTT (render-to-textures). Maybe ask on the Ogre forums? For example, [this](http://www.ogre3d.org/forums/viewtopic.php?p=121533) looks old, but maybe you can get the idea of how to place the camera content into a texture from it?
If you want to only display the camera content, you can use the textures I already have defined, and de-couple them from the cameras in the main scene, i.e. don't call the [setCameras](https://github.com/Germanunkol/OgreOculusSample/blob/master/src/Rift.cpp#L214) function.
Then you render into the textures. Maybe this already works.

I suggest that before anything else, you try to get the content of your camera into a texture in a sperate project which has nothing to do with the oculus rift. Once that's done, it should be pretty simple to render it into the other textures as well.

I believe [fakkoweb](https://github.com/fakkoweb) is working on something very similar to you - maybe consider contacting him? You can [also find him](http://www.ogre3d.org/forums/memberlist.php?mode=viewprofile&u=59766) on the Ogre forums.

Sorry I can't be of more help...

P.S. I don't think you need to lock/unlock the buffer when using blitFromMemory, I believe this already does locking internally.

**Comment by Nesh108** [comment]
Thanks for the quick reply!
I am going to try to remove the cameras and put my image data there.

I have commented out the `mRift->setCameras( mScene->getLeftCamera(), mScene->getRightCamera() );`, do I just have to write to the mLeftEyeRenderTexture and mRightEyeRenderTexture as I showed before?

P.S. I tried to remove the 'setCameras' but it removed the 2 eyes. I would like to show the image content on those same cameras.

**Comment by Germanunkol** [comment]
Do you want to only show the output from your webcams?
Or do you also want to render a virtual scene and show that as well?

In the first case, don't call mRift->setCameras, and then, yes, place your webcams' content onto the rift textures every frame.
In the second case, you'll need to add another texture to the Oculus/LeftEye and Oculus/RiftEye materials in [media/Oculus.material](https://github.com/Germanunkol/OgreOculusSample/blob/master/media/Oculus.material).
Then put the webcam content in the first texture unit, and the virtual scene textures into the second texture (however, here, you'll need to make sure the background of this texture is transparent - and I'm not sure how to do this exactly. You'll need to ask that on the ogre forums as well, or search for it...)

Again, I suggest you do two things seperately:
1. Try to render into a texture in a seperate project, which has nothing to do with this project.
2. Try to put the content of some image texture (which you load from your hard drive) onto the rift's textures.

Once you've done those two things you can "simply" combine them - instead of copying the texture data from the texture on your harddrive, copy the webcams' content onto the rift textures.

With all that said - I cannot guarantee that this works the way I think it will... but I don't see why it shouldn't.

Edit:
Ah, one thing to note here: Are you copying the image from the webcams every frame? Because the rift textures have "clearEveryFrame" set - so you have to copy the image every frame.

**Comment by Nesh108** [comment]
Hey there,

Thanks for the explanation. After tinkering around I managed to fetch the data from the camera and send it to the scene. 
The current problem is that both eyes see the same image and I am trying to figure out how to fix that.

You said that I should change the '.material' file and that kind of makes sense since in the code I couldn't understand why the scene didn't change, even after my modifications.
But then again, at the moment I am unable to make changes to the material file. I need more experience :P

P.S. I made my changes inside Scene.cpp, that was the only way I could make it work. 
For modifying the material, I tried giving a name to the 'texture_unit' for the left eye and then tried to get it from the code but I seemed to have miserably failed.

**Comment by Germanunkol** [comment]
Hi,

Just to make sure we're on the same page here: You have two cameras 
attached to the Rift, right?
Then you need to send the image from one cam to the left texture and the 
image from the other cam to the right texture.
With one camera image, it won't work - you'll never get a 3D-Effect.

As for the changing of the material file: If you're using the supplied 
cmake-script, you need to change the material file in the source folder, 
and then run the cmake script every time you changed it - it will 
re-copy the texture into the build folder. The issue is that the 
material file does not get tracked by cmake (I'm too inexperienced with 
cmake to have gotten that to work properly - sorry).
However, only change the material file if what you're trying to do is 
really to render a virtual scene above the scene of the webcams. For 
rendering two webcams, one for each eye, there should not need to be any 
changes to the material file.

**Comment by Nesh108** [comment]
Yes, I have 2 cameras and I want to stream the left one to the left eye and the right one to the right eye.

I already have the scene for both eyes (I will do some augmented reality on them) and I just want to apply to each of the eyes.

I am building the project using Eclipse, so no cmake for me at the moment.

I will be sitting on #ogre3d (freenode.net), feel free to come over and have a chat there if you've got some spare time for this small project :)

Thanks again for your help!
